kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-boot-config
  namespace: spring-application
data:
  server.port: "8080"
  spring.datasource.url: "jdbc:mysql://localhost:3306/micro_db?useSSL:FALSE"
  spring.datasource.username: root
  spring.datasource.password: Password123
  spring.datasource.driverClassName : com.mysql.jdbc.Driver
  spring.jpa.database : MYSQL
  spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5InnoDBDialect
  spring.jpa.hibernate.ddl-auto : update
  spring.jpa.generate-ddl: "true"
  spring.jpa.show-sql: "true"
  logging.level.org.hibernate : ERROR
