
apiVersion: v1
kind: PersistentVolume
metadata:
  name: isdb-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: isdb-pv
  hostPath:
    path: "/home/hungvu/isdata"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: isdb-data
  annotations:
    volume.beta.kubernetes.io/storage-class: isdb-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

